### ISSUE TITLE
Can't run my or example code on MacOS or Chrome

### ISSUE THREAD

**Issue by mzarnitsa** [jorgefspereira/plaid_flutter#142]
Can't run my or [example code](https://pub.dev/packages/plaid_flutter/example) on MacOS or Chrome

When I run example code in `macos` I get the following error:
```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
plugins.flutter.io/plaid_flutter/events:
MissingPluginException(No implementation found for method listen on channel
plugins.flutter.io/plaid_flutter/events)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676:9)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

When I run in `chrome`, I get this error
```
TypeError: Cannot read properties of undefined (reading 'create')
packages/plaid_flutter/src/platform/plaid_flutter_web.dart 78:26                create
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54              runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5              _async
packages/plaid_flutter/src/platform/plaid_flutter_web.dart 36:22                create
packages/plaid_flutter/src/core/plaid_link.dart 37:21                           create
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54              runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5              _async
packages/plaid_flutter/src/core/plaid_link.dart 35:29                           create
packages/flutter_plaid/main.dart 45:17                                          <fn>
packages/flutter/src/widgets/framework.dart 1203:30                             setState
packages/flutter_plaid/main.dart 40:5                                           [_createLinkTokenConfiguration]
packages/flutter/src/material/ink_well.dart 1170:21                             handleTap
packages/flutter/src/gestures/recognizer.dart 351:24                            invokeCallback
packages/flutter/src/gestures/tap.dart 656:11                                   handleTapUp
packages/flutter/src/gestures/tap.dart 313:5                                    [_checkUp]
packages/flutter/src/gestures/tap.dart 246:7                                    handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 703:9                             handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:7                          [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                         <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:7         forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                        [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                         route
packages/flutter/src/gestures/binding.dart 501:5                                handleEvent
packages/flutter/src/gestures/binding.dart 481:14                               dispatchEvent
packages/flutter/src/rendering/binding.dart 450:11                              dispatchEvent
packages/flutter/src/gestures/binding.dart 426:7                                [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 389:5                                handlePointerEvent
packages/flutter/src/gestures/binding.dart 336:7                                [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 305:9                                [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1423:5                              invoke1
lib/_engine/engine/platform_dispatcher.dart 336:5                               invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 405:30                                  [_sendToFramework]
lib/_engine/engine/pointer_binding.dart 225:7                                   onPointerData
lib/_engine/engine/pointer_binding.dart 1035:20                                 <fn>
lib/_engine/engine/pointer_binding.dart 948:7                                   <fn>
lib/_engine/engine/pointer_binding.dart 541:9                                   loggedHandler
dart-sdk/lib/_internal/js_dev_runtime/patch/js_allow_interop_patch.dart 188:27  _callDartFunctionFast1
```

When I target `ios`, I don't get error about missing plugin, however "Open" and "Submit Phone Number" buttons cause errors - they probably should work for the proper demo

I also checked existing issues on the subject. Found [these questions](https://github.com/flutter/flutter/issues/10912#issuecomment-310499594)

1. Fails in `chrome` and `macos`, but not in `ios`, as I mentioned
2. Did restart the app, it wasn't a hot reload
3. I found reference to Plaid plugin in Android and iOS versions of `GeneratedPluginRegistrant`, but not in `macos` one. Macos one (`macos/Flutter/GeneratedPluginRegistrant.swift`) looks like this:

```
//
//  Generated file. Do not edit.
//

import FlutterMacOS
import Foundation


func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
}
```

Is `plaid_flutter` designed to work only on Android and iOS? My target is actually Chrome.

Any help is appreciated.

**Comment by mzarnitsa** [comment]
After adding `<script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>` to `index.html`, chrome target seems to be working. But not macos.
