### ISSUE TITLE
Exception has occurred.

### ISSUE THREAD

**Issue by discoverchethan** [jorgefspereira/plaid_flutter#21]
Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method open on channel plugins.flutter.io/plaid_flutter))

I'm new to this. could you please help me out? Thanks

**Comment by discoverchethan** [comment]
```
E/flutter ( 8084): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method open on channel plugins.flutter.io/plaid_flutter)
E/flutter ( 8084): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter ( 8084): <asynchronous suspension>
E/flutter ( 8084): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter ( 8084): #2      PlaidLink.open (package:plaid_flutter/src/plaid_link.dart:159:14)
E/flutter ( 8084): #3      _MyAppState.build.<anonymous closure> (package:best_flutter_ui_templates/Plaid/plaid_test.dart:83:50)
E/flutter ( 8084): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
E/flutter ( 8084): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
E/flutter ( 8084): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter ( 8084): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter ( 8084): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter ( 8084): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:219:7)
E/flutter ( 8084): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:477:9)
E/flutter ( 8084): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:78:12)
E/flutter ( 8084): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:124:9)
E/flutter ( 8084): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter ( 8084): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:122:18)
E/flutter ( 8084): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:108:7)
E/flutter ( 8084): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter ( 8084): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter ( 8084): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter ( 8084): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter ( 8084): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter ( 8084): #21     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 8084): #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 8084): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 8084): #24     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter ( 8084): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
E/flutter ( 8084):
```

**Comment by discoverchethan** [comment]
Apparently downgrading path_provider to v1.5.0 makes it work

**Comment by jorgefspereira** [comment]
Hi @discoverchethan. I'm glad you were able to fix the issue. You can also check these questions list here [flutter/flutter#10912 (comment)](https://github.com/flutter/flutter/issues/10912#issuecomment-310499594) to find the root cause of your issue.
