### ISSUE TITLE
Can't run app because of NoClassDefFoundError

### ISSUE THREAD

**Issue by kylegraycar** [jorgefspereira/plaid_flutter#31]
I'm trying to run my app but it appears to be interrupted by some errors within `plaid_flutter`. See runtime snippet below. 

I'm on version ^1.1.6

```
[ +128 ms] sdk gphone x86 startApp
[   +6 ms] executing: /Users/kylegraycar/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.decarbonapp.decarbon.android/com.example.dcrbn3.MainActivity
[ +591 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.decarbonapp.decarbon.android/com.example.dcrbn3.MainActivity (has extras) }
[        ] Waiting for observatory port to be available...
[+548486 ms] E/AndroidRuntime(10141): FATAL EXCEPTION: main
[  +17 ms] E/AndroidRuntime(10141): Process: com.decarbonapp.decarbon.android, PID: 10141
[        ] E/AndroidRuntime(10141): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/plaid/link/result/PlaidLinkResultHandler;
[        ] E/AndroidRuntime(10141): 	at com.github.jorgefspereira.plaid_flutter.PlaidFlutterPlugin.<init>(PlaidFlutterPlugin.java:73)
[        ] E/AndroidRuntime(10141): 	at com.github.jorgefspereira.plaid_flutter.PlaidFlutterPlugin.registerWith(PlaidFlutterPlugin.java:110)
[        ] E/AndroidRuntime(10141): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:23)
[        ] E/AndroidRuntime(10141): 	at com.example.dcrbn3.MainActivity.configureFlutterEngine(MainActivity.kt:10)
[        ] E/AndroidRuntime(10141): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:181)
[        ] E/AndroidRuntime(10141): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:410)
[        ] E/AndroidRuntime(10141): 	at android.app.Activity.performCreate(Activity.java:8000)
[        ] E/AndroidRuntime(10141): 	at android.app.Activity.performCreate(Activity.java:7984)
[        ] E/AndroidRuntime(10141): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
[        ] E/AndroidRuntime(10141): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
[        ] E/AndroidRuntime(10141): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
[        ] E/AndroidRuntime(10141): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
[        ] E/AndroidRuntime(10141): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[        ] E/AndroidRuntime(10141): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[        ] E/AndroidRuntime(10141): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
[        ] E/AndroidRuntime(10141): 	at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime(10141): 	at android.os.Looper.loop(Looper.java:223)
[        ] E/AndroidRuntime(10141): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
[        ] E/AndroidRuntime(10141): 	at java.lang.reflect.Method.invoke(Native Method)
[   +3 ms] E/AndroidRuntime(10141): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[        ] E/AndroidRuntime(10141): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
[        ] E/AndroidRuntime(10141): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.plaid.link.result.PlaidLinkResultHandler" on path: DexPathList[[zip file "/data/app/~~bsmE5xQCw2h3hQN4MJ9FOg==/com.decarbonapp.decarbon.android-IKwOUSNFfROqF3dMTphAOQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~bsmE5xQCw2h3hQN4MJ9FOg==/com.decarbonapp.decarbon.android-IKwOUSNFfROqF3dMTphAOQ==/lib/x86, /data/app/~~bsmE5xQCw2h3hQN4MJ9FOg==/com.decarbonapp.decarbon.android-IKwOUSNFfROqF3dMTphAOQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
[        ] E/AndroidRuntime(10141): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
[        ] E/AndroidRuntime(10141): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[        ] E/AndroidRuntime(10141): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[        ] E/AndroidRuntime(10141): 	... 21 more
```

**Comment by jorgefspereira** [comment]
Clean your flutter project, and give a try to the new version of the plugin 2.0.0. I'm closing this issue for now. Feel free to reopen if the issue persists.
