### ISSUE TITLE
Unable to launch Plaid Link in Flutter Web due to Dart error

### ISSUE THREAD

**Issue by kylegraycar** [jorgefspereira/plaid_flutter#47]
I'm trying to run plaid_flutter on Chrome. I'm able to successfully fetch the linkToken, but when I proceed to launch Plaid Link I get this error output and the web view does not pop up: 
```
[+9623 ms] Error: PlatformException(error, TypeError: elements is not iterable, null, null)
               at Object.throw_ [as throw] (http://localhost:62381/dart_sdk.js:5333:11)
               at StandardMethodCodec.decodeEnvelope (http://localhost:62381/packages/flutter/src/services/system_channels.dart.lib.js:792:19)
               at platform_channel.MethodChannel.new._invokeMethod (http://localhost:62381/packages/flutter/src/services/system_channels.dart.lib.js:956:47)
               at _invokeMethod.next (<anonymous>)
               at http://localhost:62381/dart_sdk.js:39031:33
               at _RootZone.runUnary (http://localhost:62381/dart_sdk.js:38888:58)
               at _FutureListener.thenAwait.handleValue (http://localhost:62381/dart_sdk.js:33874:29)
               at handleValueCallback (http://localhost:62381/dart_sdk.js:34434:49)
               at Function._propagateToListeners (http://localhost:62381/dart_sdk.js:34472:17)
               at _Future.new.[_completeWithValue] (http://localhost:62381/dart_sdk.js:34314:23)
               at async._AsyncCallbackEntry.new.callback (http://localhost:62381/dart_sdk.js:34337:35)
               at Object._microtaskLoop (http://localhost:62381/dart_sdk.js:39175:13)
               at _startMicrotaskLoop (http://localhost:62381/dart_sdk.js:39181:13)
               at http://localhost:62381/dart_sdk.js:34688:9
```

This is my index.html file:
```
<!DOCTYPE` html>
<html>
<head>
  <!--
    If you are serving your web app in a path other than the root, change the
    href value below to reflect the base path you are serving from.

    The path provided below has to start and end with a slash "/" in order for
    it to work correctly.

    Fore more details:
    * https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
  -->
  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="Carbon Budgeting for Everyone">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="dcrbn3">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>Decarbon</title>
  <link rel="manifest" href="manifest.json">
</head>
<body>
  <!-- Plaid Link initialize script -->
  <script src="https://cdn.plaid.com/link/v2/stable/link-initialize.js"></script>

  <!-- This script installs service_worker.js to provide PWA functionality to
       application. For more information, see:
       https://developers.google.com/web/fundamentals/primers/service-workers -->
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('flutter-first-frame', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>

  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-app.js"></script>

  <!-- Add SDKs for Firebase products that you want to use
       https://firebase.google.com/docs/web/setup#available-libraries -->
  <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-analytics.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.0.1/firebase-firestore.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-functions.js"></script>

  <script>
  // Your web app's Firebase configuration
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  var firebaseConfig = {
    apiKey: "xxxxxx",
    authDomain: "decarbon-app.firebaseapp.com",
    databaseURL: "https://decarbon-app.firebaseio.com",
    projectId: "decarbon-app",
    storageBucket: "decarbon-app.appspot.com",
    messagingSenderId: "xxxxxxx",
    appId: "xxxxxx",
    measurementId: "xxxxxx"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  firebase.analytics();
  </script>

  <script src="main.dart.js" type="application/javascript"></script>
</body>
```

I haven't migrated my project to null safety yet, if that matters. Please let me know if there's a solution. Thank you!!!

**Comment by jorgefspereira** [comment]
Hi @kylegraycar, sorry for the late response. I've tried with the example provided in the lib and I've got no error. Have you tried using your link token with the example? Sorry again for the late response.
