### ISSUE TITLE
PlaidLink.open crashing android emulator

### ISSUE THREAD

**Issue by micaellasry** [jorgefspereira/plaid_flutter#58]
Hi everyone,

I'm getting this error when doing PlaidLink.open
Any ideas?

```
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): Failed to handle method call
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter linkTokenConfiguration
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at com.plaid.link.Plaid.create(Unknown Source:7)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at com.github.jorgefspereira.plaid_flutter.PlaidFlutterPlugin.open(PlaidFlutterPlugin.java:209)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at com.github.jorgefspereira.plaid_flutter.PlaidFlutterPlugin.onMethodCall(PlaidFlutterPlugin.java:130)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at android.os.Looper.loop(Looper.java:193)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/plaid_flutter( 8381): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 8381): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter linkTokenConfiguration, null, java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter linkTokenConfiguration
E/flutter ( 8381): 	at com.plaid.link.Plaid.create(Unknown Source:7)
E/flutter ( 8381): 	at com.github.jorgefspereira.plaid_flutter.PlaidFlutterPlugin.open(PlaidFlutterPlugin.java:209)
E/flutter ( 8381): 	at com.github.jorgefspereira.plaid_flutter.PlaidFlutterPlugin.onMethodCall(PlaidFlutterPlugin.java:130)
E/flutter ( 8381): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 8381): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/flutter ( 8381): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/flutter ( 8381): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/flutter ( 8381): 	at android.os.Handler.handleCallback(Handler.java:873)
E/flutter ( 8381): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 8381): 	at android.os.Looper.loop(Looper.java:193)
E/flutter ( 8381): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/flutter ( 8381): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8381): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter ( 8381): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter ( 8381): )
E/flutter ( 8381): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter ( 8381): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter ( 8381): <asynchronous suspension>
E/flutter ( 8381): #2      PlaidMethodChannel.open (package:plaid_flutter/src/platform/plaid_method_channel.dart:19:5)
E/flutter ( 8381): <asynchronous suspension>
E/flutter ( 8381): #3      PlaidLink.open (package:plaid_flutter/src/core/plaid_link.dart:57:5)
```

**Comment by jorgefspereira** [comment]
It seems your linkTokenConfiguration parameter is null. At least from the logs is what appears to be. Closing for now, let me know if the problem still persists.
