### ISSUE TITLE
crash on release mode 

### ISSUE THREAD

**Issue by saharvx9** [jorgefspereira/plaid_flutter#59]
hi when i running in debug mode and profile everything works ,
but in release i get this error:

version i am facing off : `2.2.0`

```
2022-01-18 09:58:41.913 6328-6328/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sahar.app, PID: 6328
    java.lang.ExceptionInInitializerError
        at g5.e.l(SourceFile:1)
        at y4.c.<clinit>(SourceFile:74)
        at t4.P.b(SourceFile:10)
        at t4.l.E(SourceFile:4)
        at t4.l$a$p.invoke(SourceFile:2)
        at t4.M$a.invoke(SourceFile:4)
        at t4.l$a.j(SourceFile:1)
        at t4.l.f(SourceFile:1)
        at D5.h$a.invoke(SourceFile:4)
        at E5.k.b(SourceFile:4)
        at D5.h.<init>(SourceFile:3)
        at com.plaid.internal.e4$b.invoke(SourceFile:1)
        at Y3.l.getValue(SourceFile:4)
        at com.plaid.internal.e2$b.invokeSuspend(SourceFile:8)
        at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:3)
        at B5.E.run(SourceFile:15)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: w4.h.values []
        at java.lang.Enum.enumValues(Enum.java:270)
        at java.lang.Enum.access$000(Enum.java:61)
        at java.lang.Enum$1.create(Enum.java:277)
        at java.lang.Enum$1.create(Enum.java:275)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
        at java.util.EnumMap.<init>(EnumMap.java:138)
        at g5.e.<clinit>(SourceFile:12)
        at g5.e.l(SourceFile:1) 
        at y4.c.<clinit>(SourceFile:74) 
        at t4.P.b(SourceFile:10) 
        at t4.l.E(SourceFile:4) 
        at t4.l$a$p.invoke(SourceFile:2) 
        at t4.M$a.invoke(SourceFile:4) 
        at t4.l$a.j(SourceFile:1) 
        at t4.l.f(SourceFile:1) 
        at D5.h$a.invoke(SourceFile:4) 
        at E5.k.b(SourceFile:4) 
        at D5.h.<init>(SourceFile:3) 
        at com.plaid.internal.e4$b.invoke(SourceFile:1) 
        at Y3.l.getValue(SourceFile:4) 
        at com.plaid.internal.e2$b.invokeSuspend(SourceFile:8) 
        at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:3) 
        at B5.E.run(SourceFile:15) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.NoSuchMethodException: w4.h.values []
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getDeclaredMethod(Class.java:2050)
        at java.lang.Enum.enumValues(Enum.java:267)
        at java.lang.Enum.access$000(Enum.java:61) 
        at java.lang.Enum$1.create(Enum.java:277) 
        at java.lang.Enum$1.create(Enum.java:275) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:63) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2428) 
        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755) 
        at java.util.EnumMap.<init>(EnumMap.java:138) 
        at g5.e.<clinit>(SourceFile:12) 
        at g5.e.l(SourceFile:1) 
        at y4.c.<clinit>(SourceFile:74) 
        at t4.P.b(SourceFile:10) 
        at t4.l.E(SourceFile:4) 
        at t4.l$a$p.invoke(SourceFile:2) 
        at t4.M$a.invoke(SourceFile:4) 
        at t4.l$a.j(SourceFile:1) 
        at t4.l.f(SourceFile:1) 
        at D5.h$a.invoke(SourceFile:4) 
        at E5.k.b(SourceFile:4) 
        at D5.h.<init>(SourceFile:3) 
        at com.plaid.internal.e4$b.invoke(SourceFile:1) 
        at Y3.l.getValue(SourceFile:4) 
        at com.plaid.internal.e2$b.invokeSuspend(SourceFile:8) 
        at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:3) 
        at B5.E.run(SourceFile:15) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
```

i think the error maybe come from progaurd that u using or the plaid official lib

**Comment by jorgefspereira** [comment]
I'll try to replicate this using the plugin example.

**Comment by Deuque** [comment]
Any fixes for this yet

**Comment by Deuque** [comment]
> I'll try to replicate this using the plugin example.

Any ideas?
