### ISSUE TITLE
App crash after calling plaid open method on Android 10+ devices

### ISSUE THREAD

**Issue by akashelaunchinfotech** [jorgefspereira/plaid_flutter#89]
Hello,
I'm facing issue while integrating Plaid Sdk on Android. App is getting crash in release when we call PlaidLink.open method.
It is working properly in debug builds, but crashes in Release build.

Here I have also attached the crash log for same.

```
E/AndroidRuntime(30121): FATAL EXCEPTION: main
E/AndroidRuntime(30121): Process: com.alstransfer, PID: 30121
E/AndroidRuntime(30121): java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
E/AndroidRuntime(30121): 	at retrofit2.k.f(SourceFile:21)
E/AndroidRuntime(30121): 	at retrofit2.w.b(SourceFile:20)
E/AndroidRuntime(30121): 	at retrofit2.v.c(SourceFile:25)
E/AndroidRuntime(30121): 	at retrofit2.v$a.invoke(SourceFile:38)
E/AndroidRuntime(30121): 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
E/AndroidRuntime(30121): 	at $Proxy2.a(Unknown Source)
E/AndroidRuntime(30121): 	at com.plaid.internal.i6$b.invokeSuspend(SourceFile:35)
E/AndroidRuntime(30121): 	at kotlin.coroutines.jvm.internal.a.resumeWith(SourceFile:12)
E/AndroidRuntime(30121): 	at kotlinx.coroutines.z0.run(SourceFile:119)
E/AndroidRuntime(30121): 	at kotlinx.coroutines.internal.l.run(SourceFile:13)
E/AndroidRuntime(30121): 	at kotlinx.coroutines.scheduling.k.run(SourceFile:3)
E/AndroidRuntime(30121): 	at kotlinx.coroutines.scheduling.a.l(SourceFile:1)
E/AndroidRuntime(30121): 	at kotlinx.coroutines.scheduling.a$c.d(SourceFile:15)
E/AndroidRuntime(30121): 	at kotlinx.coroutines.scheduling.a$c.n(SourceFile:29)
E/AndroidRuntime(30121): 	at kotlinx.coroutines.scheduling.a$c.run(Unknown Source:0)
E/AndroidRuntime(30121): 	Suppressed: kotlinx.coroutines.x0: [u2{Cancelling}@836906a, Dispatchers.Main.immediate]

```

Firebase crashlytics

```
Fatal Exception: java.lang.ClassCastException
java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
retrofit2.HttpServiceMethod.parseAnnotations (HttpServiceMethod.java:46)
retrofit2.ServiceMethod.parseAnnotations (ServiceMethod.java:39)
retrofit2.Retrofit.loadServiceMethod (Retrofit.java:202)
retrofit2.Retrofit$1.invoke (Retrofit.java:160)
java.lang.reflect.Proxy.invoke (Proxy.java:1006)
$Proxy0.a ($Proxy0.java)
com.plaid.internal.i6$b.invokeSuspend (SourceFile:3)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:106)
kotlinx.coroutines.internal.LimitedDispatcher.run (LimitedDispatcher.kt:42)
kotlinx.coroutines.scheduling.TaskImpl.run (Tasks.kt:95)
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt:570)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:750)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:677)
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt:664)
```

**Comment by bhaveshtolatwala** [comment]
I facing same issue while release builds and Apk.
