### ISSUE TITLE
Incorrect handling of exit metadata on Web

### ISSUE THREAD

**Issue by tomwyr** [jorgefspereira/plaid_flutter#92]
Flutter 3.3.10
plaid_flutter 3.0.1

After closing Plaid overlay on the initial step of the auth flow I get following data in `mapFromExitMetadata` callback:
```
{
   "status": "requires_credentials",
   "link_session_id": <link_session_id>,
   "request_id": <request_id>,
   "institution": null,
   "accounts": [],
   "account": null,
   "account_id": null,
   "transfer_status": null
}
```
which eventually throws:
```Dart
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.jsToMap (main.dart.js:66782:26)
    at PlaidFlutterPlugin_open_closure1.call$2 (main.dart.js:251226:28)
    at Object.Primitives_applyFunction (main.dart.js:6569:30)
    at Object.Function_apply (main.dart.js:12222:16)
    at _callDartFunctionFast (main.dart.js:15889:16)
    at Object.onExit (main.dart.js:15881:18)
    at Object.exit (link-initialize.js:1:110517)
    at link-initialize.js:1:101794
```

Edit: Let me double check I've properly upgraded the package to 3.0.1.

**Comment by tomwyr** [comment]
It was my local dev environment not correctly picking up the upgraded package version from from the pub cache.
Sorry for bothering. No errors in the latest version 🎉
